categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
exclude-labels:
  - 'no-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  
  $CHANGES
  
  ### A huge thanks to the following users who contributed to this release
  
  $CONTRIBUTORS
